name: dynamic_form_state
description: dynamic_form_state makes it easy to manage a changing widget state with many different types of values, for example a large input for. Initalize dynamic_form_state with any number of dynamic values with default values and access both its setState and values with ease.
version: 1.0.0
homepage: https://github.com/anovis/dynamic_form_state

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
    flutter:
      sdk: flutter
      
dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
